src/InvoiceBundle/Entity/Invoice.php
<?php

namespace InvoiceBundle\Entity;

use BookingsBundle\Entity\Booking;
use Doctrine\ORM\Mapping as ORM;

/**
 * Invoice.
 *
 * @ORM\Table(name="invoice")
 * @ORM\Entity(repositoryClass="InvoiceBundle\Repository\InvoiceRepository")
 */
class Invoice
{
    const STATUS_NEW = 'new';
    const STATUS_PAID = 'paid';
    const STATUS_PARTIALLY_PAID = 'partially paid';

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="BookingsBundle\Entity\Booking")
     * @ORM\JoinColumn(name="booking_id", referencedColumnName="id")
     */
    private $booking;

    /**
     * @var float
     *
     * @ORM\Column(name="vehicle_rent", type="float")
     */
    private $vehicleRent;

    /**
     * @var float
     *
     * @ORM\Column(name="equipment_rent", type="float", nullable=true)
     */
    private $equipmentRent = 0;

    /**
     * @var float
     *
     * @ORM\Column(name="insurance_cost", type="float", nullable=true)
     */
    private $insuranceCost;

    /**
     * @var float
     *
     * @ORM\Column(name="service_tax", type="float", nullable=true)
     */
    private $serviceTax;

    /**
     * @var float
     *
     * @ORM\Column(name="tax_rate", type="float", nullable=true)
     */
    private $taxRate;

    /**
     * @var float
     *
     * @ORM\Column(name="tax_amount", type="float", nullable=true)
     */
    private $taxAmount;

    /**
     * @var float
     *
     * @ORM\Column(name="total_amount_paybale", type="float")
     */
    private $totalAmountPaybale;

    /**
     * @var float
     *
     * @ORM\Column(name="discount_amount", type="float", nullable=true)
     */
    private $discountAmount;

    /**
     * @var float
     *
     * @ORM\Column(name="net_amount_payable", type="float")
     */
    private $netAmountPayable;

    /**
     * @var string
     *
     * @ORM\Column(name="status", type="string")
     */
    private $status = self::STATUS_NEW;

    /**
     * @var float
     *
     * @ORM\Column(name="security_deposit", type="float")
     */
    private $security_deposit;

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set booking.
     *
     * @param Booking
     *
     * @return Invoice
     */
    public function setBooking($booking)
    {
        $this->booking = $booking;

        return $this;
    }

    /**
     * Get booking.
     *
     * @return Booking
     */
    public function getBooking()
    {
        return $this->booking;
    }

    /**
     * Set vehicleRent.
     *
     * @param float $vehicleRent
     *
     * @return Invoice
     */
    public function setVehicleRent($vehicleRent)
    {
        $this->vehicleRent = $vehicleRent;

        return $this;
    }

    /**
     * Get vehicleRent.
     *
     * @return float
     */
    public function getVehicleRent()
    {
        return $this->vehicleRent;
    }

    /**
     * Set equipmentRent.
     *
     * @param float $equipmentRent
     *
     * @return Invoice
     */
    public function setEquipmentRent($equipmentRent)
    {
        $this->equipmentRent = $equipmentRent;

        return $this;
    }

    /**
     * Get equipmentRent.
     *
     * @return float
     */
    public function getEquipmentRent()
    {
        return $this->equipmentRent;
    }

    /**
     * Set insuranceCost.
     *
     * @param float $insuranceCost
     *
     * @return Invoice
     */
    public function setInsuranceCost($insuranceCost)
    {
        $this->insuranceCost = $insuranceCost;

        return $this;
    }

    /**
     * Get insuranceCost.
     *
     * @return float
     */
    public function getInsuranceCost()
    {
        return $this->insuranceCost;
    }

    /**
     * Set serviceTax.
     *
     * @param float $serviceTax
     *
     * @return Invoice
     */
    public function setServiceTax($serviceTax)
    {
        $this->serviceTax = $serviceTax;

        return $this;
    }

    /**
     * Get serviceTax.
     *
     * @return float
     */
    public function getServiceTax()
    {
        return $this->serviceTax;
    }

    /**
     * Set taxRate.
     *
     * @param float $taxRate
     *
     * @return Invoice
     */
    public function setTaxRate($taxRate)
    {
        $this->taxRate = $taxRate;

        return $this;
    }

    /**
     * Get taxRate.
     *
     * @return float
     */
    public function getTaxRate()
    {
        return $this->taxRate;
    }

    /**
     * Set totalAmountPaybale.
     *
     * @param float $totalAmountPaybale
     *
     * @return Invoice
     */
    public function setTotalAmountPaybale($totalAmountPaybale)
    {
        $this->totalAmountPaybale = $totalAmountPaybale;

        return $this;
    }

    /**
     * Get totalAmountPaybale.
     *
     * @return float
     */
    public function getTotalAmountPaybale()
    {
        return $this->totalAmountPaybale;
    }

    /**
     * Set discountAmount.
     *
     * @param float $discountAmount
     *
     * @return Invoice
     */
    public function setDiscountAmount($discountAmount)
    {
        $this->discountAmount = $discountAmount;

        return $this;
    }

    /**
     * Get discountAmount.
     *
     * @return float
     */
    public function getDiscountAmount()
    {
        return $this->discountAmount;
    }

    /**
     * Set netAmountPayable.
     *
     * @param float $netAmountPayable
     *
     * @return Invoice
     */
    public function setNetAmountPayable($netAmountPayable)
    {
        $this->netAmountPayable = $netAmountPayable;

        return $this;
    }

    /**
     * Get netAmountPayable.
     *
     * @return float
     */
    public function getNetAmountPayable()
    {
        return $this->netAmountPayable;
    }

    /**
     * @param string $status
     *
     * @return Invoice
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param float $security_deposit
     *
     * @return Invoice
     */
    public function setSecurityDeposit($security_deposit)
    {
        $this->security_deposit = $security_deposit;

        return $this;
    }

    /**
     * @return float
     */
    public function getSecurityDeposit()
    {
        return $this->security_deposit;
    }

    /**
     * @param float $taxAmount
     *
     * @return Invoice
     */
    public function setTaxAmount($taxAmount)
    {
        $this->taxAmount = $taxAmount;

        return $this;
    }

    /**
     * @return float
     */
    public function getTaxAmount()
    {
        return $this->taxAmount;
    }
}

src/InvoiceBundle/Controller/InvoiceController.php
<?php

namespace InvoiceBundle\Controller;

use InvoiceBundle\Entity\Invoice;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * Invoice controller.
 *
 * @Route("invoices")
 */
class InvoiceController extends Controller
{
    /**
     * Lists all invoice entities.
     *
     * @Route("/", name="invoices_index")
     * @Method("GET")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $invoices = $em->getRepository('InvoiceBundle:Invoice')->findAll();

        return $this->render('InvoiceBundle::index.html.twig', array(
            'invoices' => $invoices,
        ));
    }

    /**
     * Finds and displays a invoice entity.
     *
     * @Route("/{id}", name="invoices_show")
     * @Method("GET")
     *
     * @param Invoice $invoice
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function showAction(Invoice $invoice)
    {
        return $this->render('InvoiceBundle::show.html.twig', array(
            'invoice' => $invoice,
        ));
    }
}

src/InvoiceBundle/Tests/Controller/InvoiceControllerTest.php
<?php

namespace InvoiceBundle\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class InvoiceControllerTest extends WebTestCase
{
    /*
    public function testCompleteScenario()
    {
        // Create a new client to browse the application
        $client = static::createClient();

        // Go to the list view
        $crawler = $client->request('GET', '/invoices/');
        $this->assertEquals(200, $client->getResponse()->getStatusCode(), "Unexpected HTTP status code for GET /invoices/");

        // Go to the show view
        $crawler = $client->click($crawler->selectLink('show')->link());
        $this->assertEquals(200, $client->getResponse()->getStatusCode(), "Unexpected HTTP status code");
    }

    */
}

src/InvoiceBundle/Resources/views/index.html.twig
{% extends 'AppBundle::layout.html.twig' %}

{% block body %}
    <div class="card bg-white">
        <div class="card-header">
            Invoices
        </div>
        <div class="card-block">

            <div class="row">
                <div class="col-md-1"><a href="{{  path('booking_operations') }}" class="btn btn-primary">Dashboard</a></div>
                {#<div class="col-md-1"><a href="{{  path('employees_new') }}" class="btn btn-primary">New Employee</a></div>#}
            </div><br />

            <table class="table table-bordered table-condensed datatable m-b-0">
                <thead>
                <tr>
                    <th>Booking ID</th>
                    <th>Customer name</th>
                    <th>Vehicle rent</th>
                    <th>Tax Rate</th>
                    <th>Tax Amount</th>
                    <th>Deposit Amount</th>
                    <th>Net amount payable</th>
                    <th>Total amount paybale</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for invoice in invoices %}
                    <tr>
                        <td>{{ invoice.booking.id }}</td>
                        <td>{{ invoice.booking.customer.name }}</td>
                        <td>{{ invoice.vehicleRent }}</td>
                        <td>{{ invoice.taxRate }}</td>
                        <td>{{ invoice.taxAmount }}</td>
                        <td>{{ invoice.securityDeposit }}</td>
                        <td>{{ invoice.netAmountPayable }}</td>
                        <td>{{ invoice.totalAmountPaybale }}</td>
                        <td>
                            <a href="{{ path('invoices_show', { 'id': invoice.id }) }}"><span class="fa fa-download"></span></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

{% block javascripts %}

    {{ parent() }}

    <!-- page scripts -->
    <script src="{{ asset('assets/vendor/datatables/media/js/jquery.dataTables.js') }}"></script>
    <!-- end page scripts -->
    <!-- initialize page scripts -->
    <script src="{{ asset('assets/vendor/datatables/media/js/dataTables.bootstrap.js') }}"></script>
    <script type="text/javascript">
        $('.datatable').dataTable();
    </script>
    <!-- end initialize page scripts -->

{% endblock %}

src/InvoiceBundle/Resources/views/show.html.twig
{% extends 'AppBundle::layout.html.twig' %}

{% block body %}
    <style>
        .invoice-box{
            max-width:800px;
            margin:auto;
            padding:30px;
            border:1px solid #eee;
            box-shadow:0 0 10px rgba(0, 0, 0, .15);
            font-size:16px;
            line-height:24px;
            font-family:'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color:#555;
            background-color: #ffffff !important;
        }

        .invoice-box table{
            width:100%;
            line-height:inherit;
            text-align:left;
        }

        .invoice-box table td{
            padding:5px;
            vertical-align:top;
        }

        .invoice-box table tr td:nth-child(2){
            text-align:right;
        }

        .invoice-box table tr.top table td{
            padding-bottom:20px;
        }

        .invoice-box table tr.top table td.title{
            font-size:45px;
            line-height:45px;
            color:#333;
        }

        .invoice-box table tr.information table td{
            padding-bottom:40px;
        }

        .invoice-box table tr.heading td{
            background:#eee;
            border-bottom:1px solid #ddd;
            font-weight:bold;
        }

        .invoice-box table tr.details td{
            padding-bottom:20px;
        }

        .invoice-box table tr.item td{
            border-bottom:1px solid #eee;
        }

        .invoice-box table tr.item.last td{
            border-bottom:none;
        }

        .invoice-box table tr.total td:nth-child(2){
            border-top:2px solid #eee;
            font-weight:bold;
        }

        @media only screen and (max-width: 600px) {
            .invoice-box table tr.top table td{
                width:100%;
                display:block;
                text-align:center;
            }

            .invoice-box table tr.information table td{
                width:100%;
                display:block;
                text-align:center;
            }
        }
    </style>
    <div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr class="top">
                <td colspan="2">
                    <table>
                        <tr>
                            <td class="title">
                                <img src="https://luxervrental.com/wp-content/uploads/2015/11/LUXE_RV_P_Gradient_RGB_Gold.png" style="width:100%; max-width:300px;">
                            </td>

                            <td>
                                Invoice #: {{ invoice.id }}<br>
                                Created: {{ invoice.booking.pickUpDate|date('m/d/Y') }}<br>
                                Due: {{ invoice.booking.pickUpDate|date('m/d/Y') }}
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr class="information">
                <td colspan="2">
                    <table>
                        <tr>
                            <td>
                                Next Step Webs, Inc.<br>
                                12345 Sunny Road<br>
                                Sunnyville, TX 12345
                            </td>

                            <td>
                                {{ invoice.booking.customer.name }}<br>
                                {% if invoice.booking.customer.billing %}
                                    {{ invoice.booking.customer.billing }}<br />
                                {% endif %}
                                {{ invoice.booking.customer.email }}
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            {#<tr class="heading">
                <td>Payments</td>
                <td></td>
            </tr>
            <tr class="details">
                <td>Credit Card</td>
                <td>0</td>
            </tr>#}

            <tr class="details">
                <td>Booking # {{ invoice.booking.id }}</td>
                <td>{{ invoice.booking.pickUpDate|date('m/d/Y H:i') }} - {{ invoice.booking.dropOffDate|date('m/d/Y H:i') }}</td>
            </tr>

            <tr class="item">
                <td>Vehicle Rent</td>
                <td>${{ invoice.vehicleRent }}</td>
            </tr>
            <tr class="item">
                <td>Tax ({{ invoice.taxRate }}%)</td>
                <td>${{ invoice.taxAmount }}</td>
            </tr>
            <tr class="item last">
                <td>Security Deposit</td>
                <td>${{ invoice.securityDeposit }}</td>
            </tr>
            <tr class="total">
                <td></td>
                <td>
                    Total: ${{ invoice.totalAmountPaybale }}
                </td>
            </tr>
        </table>
    </div>
{% endblock %}